---
title: "STAT-427 Final Project"
author: "James, Gabe, Tom"
format: html
editor: visual
output:
  html_document: 
    toc: yes
    toc_depth: 2
    number_sections: no
---

## 

# An "executive" summary that succinctly describes the most important findings and recommendations in a manner that entices the viewer/reader to engage more with your poster or report.

# Data Cleaning 

```{r}
library(readr)
data <- read_csv("TIMES_WorldUniversityRankings_2024.csv")
data_clean <- data[, c("rank", "name","scores_overall","scores_teaching","scores_research","scores_citations","scores_industry_income","scores_international_outlook","location","stats_number_students","stats_student_staff_ratio", "stats_pc_intl_students", "stats_female_male_ratio")]

```

# Method 1 -

# Method 2 -

# Method 3 -

# Method 4 -

# Method 5 -

# Method 6 -

# Identify the data source, describe the original data, and any challenges or choices in cleaning the data for analysis.

# Identify the stakeholders in the analysis and its outcomes. Assess any ethical implications of the data (collection methods, sources, structure) or the choices made in the analysis (grouping, selection, etc.) or any other responsible data science concerns for implementation.

# Summarize Findings

# Offer recommendations for implementation or additional work

# References
